name: Nightly Build
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up C++ environment
        uses: aminya/setup-cpp@v1
        with:
          compiler: llvm
          cmake: true
          ninja: true

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y llvm-19

      - name: Install vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git /home/runner/vcpkg
          cd /home/runner/vcpkg
          ./bootstrap-vcpkg.sh

      - name: Install ANTLR4-runtime v4.12
        run: |
          /home/runner/vcpkg/vcpkg install antlr4-runtime:x64-linux


      - name: Configure CMake
        run: cmake -B build \
          -DCMAKE_TOOLCHAIN_FILE=/home/runner/vcpkg/scripts/buildsystems/vcpkg.cmake \
          -DCMAKE_BUILD_TYPE=Release .

      - name: Build project
        run: cmake --build build --config Release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: nightly-build
          path: build/